version: "3"

services:
  db:
    image: postgres
    volumes:
      - postgres_vol:/var/lib/postgresql/data
    env_file:
      - .env
  web:
    build: 
      context: .
    command: bash -c "python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
    env_file:
      - .env
    ports:
      - "${WEB_PORT}:8000"
    depends_on:
      - db

  redis:
    image: redis
  
  celery:
    build: .
    command: celery -A core worker -l ${CELERY_LOG_LEVEL}
    volumes:
      - .:/code
    env_file:
      - .env
    depends_on:
      - redis
      - web

volumes:
  postgres_vol:
